package projectplanner;

import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;


public class ProjectFrame extends javax.swing.JFrame {
    
    
    private ProjectManager manager;
    
    public ProjectFrame(Project project) {
        this.manager = new ProjectManager(project, project);
        initComponents();
        setElements();
        updateDetails();
        updateTable();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTaskFrame = new javax.swing.JFrame();
        taskNameLabel = new javax.swing.JLabel();
        taskNameField = new javax.swing.JTextField();
        startDateChooser2 = new com.toedter.calendar.JDateChooser();
        endDateChooser2 = new com.toedter.calendar.JDateChooser();
        startDateLabel2 = new javax.swing.JLabel();
        endDateLabel2 = new javax.swing.JLabel();
        okAddTaskButton = new javax.swing.JButton();
        cancelAddTaskButton = new javax.swing.JButton();
        settingsFrame = new javax.swing.JFrame();
        projectNameSetting = new javax.swing.JTextField();
        projectNameLabelSetting = new javax.swing.JLabel();
        budgetLabelSetting = new javax.swing.JLabel();
        budgetSetting = new javax.swing.JTextField();
        startDateLabelSetting = new javax.swing.JLabel();
        startDateChooserSetting = new com.toedter.calendar.JDateChooser();
        endDateLabelSetting = new javax.swing.JLabel();
        endDateChooserSetting = new com.toedter.calendar.JDateChooser();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addResourceFrame = new javax.swing.JFrame();
        resourceNameField = new javax.swing.JTextField();
        resourceNameLabel = new javax.swing.JLabel();
        resourceCostLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        cancelResourceButton = new javax.swing.JButton();
        resourceCostField = new javax.swing.JTextField();
        tableScrollPane = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();
        detailFrame = new javax.swing.JInternalFrame();
        attPane = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        startDateChooser = new com.toedter.calendar.JDateChooser();
        endDateChooser = new com.toedter.calendar.JDateChooser();
        endDateLabel = new javax.swing.JLabel();
        finishedCheckBox = new javax.swing.JCheckBox();
        taskProgressLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        progressValueLabel = new javax.swing.JLabel();
        applyButton = new javax.swing.JButton();
        costValue = new javax.swing.JLabel();
        toSubtaskButton = new javax.swing.JButton();
        noteScrollPane = new javax.swing.JScrollPane();
        noteArea = new javax.swing.JTextArea();
        resourcesScrollPane = new javax.swing.JScrollPane();
        resourceTable = new javax.swing.JTable();
        addResourceButton = new javax.swing.JButton();
        deleteResourceButton = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        projectNameLabel = new javax.swing.JLabel();
        projectName = new javax.swing.JLabel();
        deadLineLabel = new javax.swing.JLabel();
        deadLine = new javax.swing.JLabel();
        progressLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        totalCostLabel = new javax.swing.JLabel();
        totalCost = new javax.swing.JLabel();
        budgetLabel = new javax.swing.JLabel();
        projectBudget = new javax.swing.JLabel();
        orderBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        taskNumLabel = new javax.swing.JLabel();
        taskNum = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        addMenu = new javax.swing.JMenu();
        addTask = new javax.swing.JMenuItem();
        deleteTask = new javax.swing.JMenuItem();
        settingsMenu = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        settingsMenuItem = new javax.swing.JMenuItem();

        addTaskFrame.setTitle("Add a task");
        addTaskFrame.setBounds(new java.awt.Rectangle(200, 100, 400, 230));

        taskNameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        taskNameLabel.setText("Task name:");

        taskNameField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        startDateLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        startDateLabel2.setText("Start date:");

        endDateLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        endDateLabel2.setText("End date:");

        okAddTaskButton.setText("OK");
        okAddTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okAddTaskButtonActionPerformed(evt);
            }
        });

        cancelAddTaskButton.setText("Cancel");
        cancelAddTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddTaskButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addTaskFrameLayout = new javax.swing.GroupLayout(addTaskFrame.getContentPane());
        addTaskFrame.getContentPane().setLayout(addTaskFrameLayout);
        addTaskFrameLayout.setHorizontalGroup(
            addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskFrameLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(taskNameLabel)
                    .addComponent(startDateLabel2)
                    .addComponent(endDateLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(taskNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(startDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(addTaskFrameLayout.createSequentialGroup()
                            .addComponent(cancelAddTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(okAddTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(endDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        addTaskFrameLayout.setVerticalGroup(
            addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskFrameLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addTaskFrameLayout.createSequentialGroup()
                        .addGroup(addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taskNameLabel)
                            .addComponent(taskNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(startDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(startDateLabel2))
                .addGap(18, 18, 18)
                .addGroup(addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(endDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateLabel2))
                .addGap(18, 18, 18)
                .addGroup(addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okAddTaskButton)
                    .addComponent(cancelAddTaskButton))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        settingsFrame.setTitle("Project Settings");
        settingsFrame.setBounds(new java.awt.Rectangle(200, 200, 430, 240));

        projectNameLabelSetting.setText("Project name:");

        budgetLabelSetting.setText("Budget:");

        startDateLabelSetting.setText("From:");

        endDateLabelSetting.setText("To:");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsFrameLayout = new javax.swing.GroupLayout(settingsFrame.getContentPane());
        settingsFrame.getContentPane().setLayout(settingsFrameLayout);
        settingsFrameLayout.setHorizontalGroup(
            settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsFrameLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsFrameLayout.createSequentialGroup()
                        .addGroup(settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(budgetLabelSetting)
                            .addComponent(projectNameLabelSetting))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectNameSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(budgetSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(settingsFrameLayout.createSequentialGroup()
                        .addGroup(settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(settingsFrameLayout.createSequentialGroup()
                                .addComponent(startDateLabelSetting)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startDateChooserSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(settingsFrameLayout.createSequentialGroup()
                                .addComponent(endDateLabelSetting)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endDateChooserSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        settingsFrameLayout.setVerticalGroup(
            settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsFrameLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectNameLabelSetting))
                .addGap(22, 22, 22)
                .addGroup(settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(budgetLabelSetting)
                    .addComponent(budgetSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startDateLabelSetting)
                    .addComponent(startDateChooserSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateLabelSetting)
                    .addComponent(endDateChooserSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        addResourceFrame.setSize(new java.awt.Dimension(380, 180));

        resourceNameField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        resourceNameField.setText("new resource");

        resourceNameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        resourceNameLabel.setText("Resource name:");

        resourceCostLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        resourceCostLabel.setText("Cost:");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cancelResourceButton.setText("Cancel");
        cancelResourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelResourceButtonActionPerformed(evt);
            }
        });

        resourceCostField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        resourceCostField.setText("0");

        javax.swing.GroupLayout addResourceFrameLayout = new javax.swing.GroupLayout(addResourceFrame.getContentPane());
        addResourceFrame.getContentPane().setLayout(addResourceFrameLayout);
        addResourceFrameLayout.setHorizontalGroup(
            addResourceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addResourceFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addResourceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resourceNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resourceCostLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addResourceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addResourceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(addResourceFrameLayout.createSequentialGroup()
                            .addComponent(cancelResourceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(resourceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resourceCostField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );
        addResourceFrameLayout.setVerticalGroup(
            addResourceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addResourceFrameLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(addResourceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resourceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resourceNameLabel))
                .addGap(18, 18, 18)
                .addGroup(addResourceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resourceCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resourceCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addResourceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(cancelResourceButton))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        tableScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        taskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        taskTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        taskTable.setCellSelectionEnabled(false);
        taskTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        taskTable.setMinimumSize(new java.awt.Dimension(100, 320));
        taskTable.setPreferredSize(null);
        taskTable.setRowHeight(20);
        taskTable.setRowSelectionAllowed(true);
        taskTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        taskTable.setShowGrid(true);
        taskTable.getTableHeader().setReorderingAllowed(false);
        tableScrollPane.setViewportView(taskTable);
        taskTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        /* listens to selection events */
        this.taskTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    updateDetails();
                }
            }
        });

        detailFrame.setVisible(true);

        attPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titleLabel.setText("Title");

        costLabel.setText("Cost");

        startDateLabel.setText("From");

        endDateLabel.setText("To");

        finishedCheckBox.setText("Finished");
        finishedCheckBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        taskProgressLabel.setText("Progress");

        titleField.setText("jTextField1");

        progressValueLabel.setText("0");

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        costValue.setText("Cost");

        toSubtaskButton.setText("To Subtask");
        toSubtaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toSubtaskButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout attPaneLayout = new javax.swing.GroupLayout(attPane);
        attPane.setLayout(attPaneLayout);
        attPaneLayout.setHorizontalGroup(
            attPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(attPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attPaneLayout.createSequentialGroup()
                        .addGroup(attPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(startDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(costLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(attPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(attPaneLayout.createSequentialGroup()
                                .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(endDateLabel))
                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costValue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(attPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(endDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(toSubtaskButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(attPaneLayout.createSequentialGroup()
                        .addGroup(attPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(finishedCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(attPaneLayout.createSequentialGroup()
                                .addComponent(taskProgressLabel)
                                .addGap(18, 18, 18)
                                .addComponent(progressValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        attPaneLayout.setVerticalGroup(
            attPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(attPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toSubtaskButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costLabel)
                    .addComponent(costValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startDateLabel)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateLabel)
                    .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishedCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskProgressLabel)
                    .addComponent(progressValueLabel)
                    .addComponent(applyButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        noteScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        noteScrollPane.setViewportView(null);

        noteArea.setColumns(20);
        noteArea.setLineWrap(true);
        noteArea.setRows(5);
        noteArea.setText("This is where you can write some notes or comments:\n");
        noteScrollPane.setViewportView(noteArea);

        resourcesScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        resourceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Resource", "Cost"
            }
        ));
        resourceTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        resourcesScrollPane.setViewportView(resourceTable);

        addResourceButton.setText("Add resource");
        addResourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResourceButtonActionPerformed(evt);
            }
        });

        deleteResourceButton.setText("Delete resource");
        deleteResourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteResourceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailFrameLayout = new javax.swing.GroupLayout(detailFrame.getContentPane());
        detailFrame.getContentPane().setLayout(detailFrameLayout);
        detailFrameLayout.setHorizontalGroup(
            detailFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resourcesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(noteScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(attPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailFrameLayout.createSequentialGroup()
                        .addComponent(deleteResourceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addResourceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        detailFrameLayout.setVerticalGroup(
            detailFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noteScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resourcesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addResourceButton)
                    .addComponent(deleteResourceButton)))
        );

        topPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        projectNameLabel.setText("Project:");

        projectName.setText("xxx");

        deadLineLabel.setText("Deadline:");

        deadLine.setText("01-05-2024");

        progressLabel.setText("Progress:");

        progressBar.setValue(50);
        progressBar.setStringPainted(true);

        totalCostLabel.setText("Total Cost:");

        totalCost.setText("$2123");

        budgetLabel.setText("Budget:");

        projectBudget.setText("$2123");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(deadLineLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deadLine, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(projectNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projectName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(totalCostLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(budgetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projectBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(progressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(projectName)
                    .addComponent(totalCostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalCost)
                    .addComponent(budgetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(projectBudget))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deadLineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deadLine)))
                .addContainerGap())
        );

        orderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Deadline", "Start", "Duration", "Cost" }));
        orderBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                orderBoxItemStateChanged(evt);
            }
        });

        jLabel1.setText("Order:");

        taskNumLabel.setText("Number of  tasks:");

        taskNum.setText("xxx");

        addMenu.setText("Edit");

        addTask.setText("Add Task");
        addTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskActionPerformed(evt);
            }
        });
        addMenu.add(addTask);

        deleteTask.setText("Delete Task");
        deleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTaskActionPerformed(evt);
            }
        });
        addMenu.add(deleteTask);

        menuBar.add(addMenu);

        settingsMenu.setText("Project");

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        settingsMenu.add(saveMenuItem);

        settingsMenuItem.setText("Settings");
        settingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsMenuItemActionPerformed(evt);
            }
        });
        settingsMenu.add(settingsMenuItem);

        menuBar.add(settingsMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(taskNumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(taskNum, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableScrollPane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(detailFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(taskNumLabel)
                            .addComponent(taskNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tableScrollPane))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(detailFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskActionPerformed
        this.taskNameField.setText("new task");
        this.startDateChooser2.setDate(null);
        this.endDateChooser2.setDate(null);
        this.addTaskFrame.show(); // a new window
    }//GEN-LAST:event_addTaskActionPerformed

    private void okAddTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okAddTaskButtonActionPerformed
        // adding a new task
        try {
            this.manager.newTask(this.taskNameField.getText(), this.startDateChooser2.getDate(), this.endDateChooser2.getDate());
            this.addTaskFrame.dispose();
            this.updateTable();
        } catch (Exception e) {
            e.printStackTrace();
            // error message
            JOptionPane.showMessageDialog(this, "Please enter valid data.\n"
                    + "1. The fields can't be left empty\n2. End date cannot be before start date", "Error", JOptionPane.WARNING_MESSAGE);
        }

        
    }//GEN-LAST:event_okAddTaskButtonActionPerformed

    private void cancelAddTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddTaskButtonActionPerformed
        this.addTaskFrame.dispose();
    }//GEN-LAST:event_cancelAddTaskButtonActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        try {
            this.manager.getProject().save();
        } catch (Exception ex) {
            ex.printStackTrace();
        }    
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void deleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTaskActionPerformed
        if (this.taskTable.getSelectedRow()!=-1) {
            this.manager.deleteTask(this.taskTable.getSelectedRow());
            this.updateTable();
        }
    }//GEN-LAST:event_deleteTaskActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            this.manager.changeSettings(this.projectNameSetting.getText(), Float.valueOf(this.budgetSetting.getText()), this.startDateChooserSetting.getDate(), this.endDateChooserSetting.getDate());
            this.setElements();
            this.settingsFrame.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.settingsFrame.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void settingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsMenuItemActionPerformed
        this.projectNameSetting.setText(this.manager.getProject().getTitle());
        this.budgetSetting.setText(this.manager.getProject().getBudget()+"");
        this.startDateChooserSetting.setDate(this.manager.getProject().getStartDate());
        this.endDateChooserSetting.setDate(this.manager.getProject().getEndDate());
        this.settingsFrame.setVisible(true);
    }//GEN-LAST:event_settingsMenuItemActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        try {
            this.manager.applyChanges(this.taskTable.getSelectedRow(), 
                                      this.noteArea.getText(), 
                                      this.titleField.getText(), 
                                      this.startDateChooser.getDate(), 
                                      this.endDateChooser.getDate(), 
                                      this.finishedCheckBox.isSelected());
            this.updateTable();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Something went wrong", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_applyButtonActionPerformed

    private void addResourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResourceButtonActionPerformed
        if (this.taskTable.getSelectedRow()==-1) {
            JOptionPane.showMessageDialog(this, "Choose a task first", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            this.resourceNameField.setText("");
            this.resourceCostField.setText("0");
            this.addResourceFrame.setVisible(true);             
        }
       
    }//GEN-LAST:event_addResourceButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            this.manager.addResource(this.resourceNameField.getText(), Float.valueOf(this.resourceCostField.getText()), this.taskTable.getSelectedRow());
            this.updateDetails();
            this.updateTable();
            this.addResourceFrame.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid input", "Error", JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelResourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelResourceButtonActionPerformed
        // closes the window
        this.addResourceFrame.dispose();
    }//GEN-LAST:event_cancelResourceButtonActionPerformed

    private void deleteResourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteResourceButtonActionPerformed
        int taskRow = this.taskTable.getSelectedRow();
        int resourceRow = this.resourceTable.getSelectedRow();
        if (taskRow != -1 && resourceRow != -1) {
            System.out.println("yes");
            this.manager.deleteResource(taskRow, resourceRow);
            this.updateDetails();
            this.updateTable();
        }
    }//GEN-LAST:event_deleteResourceButtonActionPerformed

    private void toSubtaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toSubtaskButtonActionPerformed
        // open a new window 
        int taskRow = this.taskTable.getSelectedRow();
        if (taskRow != -1) {
            TaskFrame tf = new TaskFrame(this.manager.getTask(taskRow), this.manager.getProject());
            tf.setTitle(this.manager.getProject().getTitle()+": "+this.manager.getTask(taskRow).getTitle());
        }
    }//GEN-LAST:event_toSubtaskButtonActionPerformed

    private void orderBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_orderBoxItemStateChanged
        // when a new item is selected
        if(evt.getStateChange()==1) {
            this.updateTable();
        }
    }//GEN-LAST:event_orderBoxItemStateChanged

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        setElements();
        updateDetails();
        updateTable();
    }//GEN-LAST:event_formWindowGainedFocus
    
    private void setElements() {
        // sets the details shown in the upper panel of the window
        this.projectName.setText(this.manager.getProject().getTitle());
        this.totalCost.setText(String.valueOf(this.manager.getProject().getCost()));
        SimpleDateFormat sdf = new SimpleDateFormat("MMM dd yyyy"); // date format
        this.deadLine.setText(sdf.format(this.manager.getProject().getEndDate()));
        this.progressBar.setValue((int)(this.manager.getProject().getProgress() * 100));
        this.progressBar.setString(String.format("%.2f", this.manager.getProject().getProgress() * 100) + "%");
        this.projectBudget.setText(String.valueOf(this.manager.getProject().getBudget()));
        // sets the maximum and minimum selectable dates according to the project
        this.startDateChooser.setMinSelectableDate(this.manager.getProject().getStartDate());
        this.startDateChooser.setMaxSelectableDate(this.manager.getProject().getEndDate());
        this.startDateChooser2.setMinSelectableDate(this.manager.getProject().getStartDate());
        this.startDateChooser2.setMaxSelectableDate(this.manager.getProject().getEndDate());
        this.endDateChooser.setMinSelectableDate(this.manager.getProject().getStartDate());
        this.endDateChooser.setMaxSelectableDate(this.manager.getProject().getEndDate());        
        this.endDateChooser2.setMinSelectableDate(this.manager.getProject().getStartDate());
        this.endDateChooser2.setMaxSelectableDate(this.manager.getProject().getEndDate());
    }
    
    private void updateTable() {
        int row = this.taskTable.getSelectedRow(); // pre-store what's been selected
        this.taskNum.setText(String.valueOf(this.manager.getProject().getTaskNum())); // set the task count
        int newRow = this.manager.refreshTable(this.orderBox.getSelectedItem().toString(), row); // refreshes the table accordingly
        DefaultTableModel model = new DefaultTableModel(this.manager.getData(), this.manager.getColumns()) {
            /* prevents user from editing the cells */
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.taskTable.setModel(model); // update
        if (newRow!=-1 && this.taskTable.getRowCount()!=0) this.taskTable.setRowSelectionInterval(newRow, newRow); // this is to keep the row selected after updating
    }
    
    private void updateResourceTable() {
        // update the resource table
        DefaultTableModel model = new DefaultTableModel(this.manager.getResources(this.taskTable.getSelectedRow()),
                new String[] {"Resource", "Cost"}) {
                /* not editable */
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
        };
        this.resourceTable.setModel(model);    
    }
    
    // this code will be executed each time a new row is selected
    public void updateDetails() {
        try {
            if (this.taskTable.getSelectedRow()!=-1){
                this.toSubtaskButton.setEnabled(true);
                Task t = this.manager.getTask(this.taskTable.getSelectedRow()); 
                this.noteArea.setText(t.getNote());
                this.titleField.setText(t.getTitle());
                this.costValue.setText(t.getCost()+"");
                this.startDateChooser.setDate(t.getStartDate());
                this.endDateChooser.setDate(t.getEndDate());
                this.finishedCheckBox.setSelected(t.isFinished());
                this.progressValueLabel.setText(t.getProgress() * 100 + "%");
                this.setElements();
                this.updateResourceTable();
            } else {
                // clear everything
                this.noteArea.setText("");
                this.titleField.setText("");
                this.costValue.setText("");
                this.startDateChooser.setDate(null);
                this.endDateChooser.setDate(null);
                this.finishedCheckBox.setSelected(false);
                this.progressValueLabel.setText("");
                this.updateResourceTable();
                this.toSubtaskButton.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong", "Error", JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JMenu addMenu;
    private javax.swing.JButton addResourceButton;
    private javax.swing.JFrame addResourceFrame;
    private javax.swing.JMenuItem addTask;
    private javax.swing.JFrame addTaskFrame;
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel attPane;
    private javax.swing.JLabel budgetLabel;
    private javax.swing.JLabel budgetLabelSetting;
    private javax.swing.JTextField budgetSetting;
    private javax.swing.JButton cancelAddTaskButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelResourceButton;
    private javax.swing.JLabel costLabel;
    private javax.swing.JLabel costValue;
    private javax.swing.JLabel deadLine;
    private javax.swing.JLabel deadLineLabel;
    private javax.swing.JButton deleteResourceButton;
    private javax.swing.JMenuItem deleteTask;
    private javax.swing.JInternalFrame detailFrame;
    private com.toedter.calendar.JDateChooser endDateChooser;
    private com.toedter.calendar.JDateChooser endDateChooser2;
    private com.toedter.calendar.JDateChooser endDateChooserSetting;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JLabel endDateLabel2;
    private javax.swing.JLabel endDateLabelSetting;
    private javax.swing.JCheckBox finishedCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextArea noteArea;
    private javax.swing.JScrollPane noteScrollPane;
    private javax.swing.JButton okAddTaskButton;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> orderBox;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JLabel progressValueLabel;
    private javax.swing.JLabel projectBudget;
    private javax.swing.JLabel projectName;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JLabel projectNameLabelSetting;
    private javax.swing.JTextField projectNameSetting;
    private javax.swing.JTextField resourceCostField;
    private javax.swing.JLabel resourceCostLabel;
    private javax.swing.JTextField resourceNameField;
    private javax.swing.JLabel resourceNameLabel;
    private javax.swing.JTable resourceTable;
    private javax.swing.JScrollPane resourcesScrollPane;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JFrame settingsFrame;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JMenuItem settingsMenuItem;
    private com.toedter.calendar.JDateChooser startDateChooser;
    private com.toedter.calendar.JDateChooser startDateChooser2;
    private com.toedter.calendar.JDateChooser startDateChooserSetting;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JLabel startDateLabel2;
    private javax.swing.JLabel startDateLabelSetting;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTextField taskNameField;
    private javax.swing.JLabel taskNameLabel;
    private javax.swing.JLabel taskNum;
    private javax.swing.JLabel taskNumLabel;
    private javax.swing.JLabel taskProgressLabel;
    private javax.swing.JTable taskTable;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton toSubtaskButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel totalCost;
    private javax.swing.JLabel totalCostLabel;
    // End of variables declaration//GEN-END:variables
}
